name: jest

on: [push, pull_request]

jobs:
  jest:


    runs-on: ubuntu-latest


    strategy:
      matrix:
        node-version: [13.x]


    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: make install
      - name: run jest
        run: make jest
